name: cleanse

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  schedule:
    - cron: "0 0 1 * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.18.3"

      # Runs a set of commands using the runners shell
      - name: Run script
        run: |
          go run main.go -g ${{ secrets.TARGET_GUILD_ID }} -t ${{ secrets.SOAP_DISCORD_TOKEN }}
